version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: alfaville/starwar
    ports:
      - "9000:9000"
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
    depends_on:
      - postgres
    networks:
      - backend
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:9.6
    restart: always
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_DB=startwars
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres #change from file path
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres-data:

networks:
  backend:
