spring:
  h2.console:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/startwars
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging.level.org.zalando.logbook: TRACE