server:
  servlet.context-path: /starwars-test
  port: 9000

logging.level.org.zalando.logbook: TRACE

people-stars:
  ribbon:
    listOfServers: https://swapi.dev/api/

feign:
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
#  datasource:
#    url:
#    username: postgres
#    password: postgres
#    driver-class-name:
#  jpa:
#    show-sql: true
#    properties.hibernate.format_sql: true
#    hibernate.ddl-auto: none