server:
  servlet.context-path: /starwars-test
  port: 9000

feign:
  hystrix:
    enabled: true
  client:
    config:
      feignName:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  swapi:
    urlBase: https://swapi.dev/api/
    nameService: stars-api

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
  application:
    name: starwars-test
  flyway:
    locations: "classpath:db/migration"